name: Publish
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Repack
      run: mvn -B -Drelease.version=${{ github.event.release.tag_name }} -s ${{ github.workspace }}/settings.xml package
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Attach rpm to release
      uses: softprops/action-gh-release@v1
      with:
        files: target/rpm/com.teragrep-bos_01/RPMS/noarch/com.teragrep-bos_01-${{ github.event.release.tag_name }}-${{ github.run_number }}.noarch.rpm
